# Generated by Django 3.0.4 on 2020-03-27 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidfitness', '0002_completedmile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedmile',
            name='user',
        ),
        migrations.DeleteModel(
            name='DailyMile',
        ),
        migrations.DeleteModel(
            name='CompletedMile',
        ),
    ]
