# Generated by Django 3.0.4 on 2020-03-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('covidfitness', '0003_auto_20200327_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_type', models.CharField(max_length=200)),
                ('reps', models.IntegerField()),
                ('sport', models.TextField()),
            ],
        ),
    ]
