# Generated by Django 3.0.4 on 2020-03-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidfitness', '0006_completedchallenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchallenge',
            name='failed',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='repeat',
            field=models.BooleanField(blank=True),
        ),
    ]
