# Generated by Django 3.0.4 on 2020-03-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidfitness', '0009_auto_20200327_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchallenge',
            name='repeat',
            field=models.BooleanField(blank=True),
        ),
    ]
