# Generated by Django 3.0.4 on 2020-03-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidfitness', '0010_auto_20200327_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchallenge',
            name='repeat',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
