# Generated by Django 3.0.4 on 2020-03-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidfitness', '0012_remove_userchallenge_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallenge',
            name='repeat',
            field=models.BooleanField(default=True),
        ),
    ]
