# Generated by Django 3.0.4 on 2020-03-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidfitness', '0020_challenge_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedchallenge',
            name='photo',
            field=models.FileField(blank=True, upload_to='challenge_photos'),
        ),
    ]
