# Generated by Django 3.0.4 on 2020-03-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidfitness', '0021_auto_20200327_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchallenge',
            name='failed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
