# Generated by Django 3.2.4 on 2021-06-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokens',
            name='eip_score',
            field=models.SmallIntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='init_supply',
            field=models.DecimalField(decimal_places=6, default='0', max_digits=15),
        ),
    ]
