# Generated by Django 3.2.4 on 2021-06-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_auto_20210620_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='init_supply',
            field=models.DecimalField(decimal_places=8, default='0', max_digits=17),
        ),
    ]
